image: hashicorp/terraform:1.5.7

pipelines:
  default:
    - step:
        oidc: true
        script:
          - cd environments/dev
          - export AWS_REGION=ap-south-1
          - export AWS_ROLE_ARN=arn:aws:iam::533266997711:role/pipeline-oidc
          - export AWS_WEB_IDENTITY_TOKEN_FILE=$(pwd)/web-identity-token

          - echo $BITBUCKET_STEP_OIDC_TOKEN > $AWS_WEB_IDENTITY_TOKEN_FILE

          - terraform init
          - terraform plan 
          - terraform apply -auto-approve